// import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import { uuid } from "uuid"

export const getStaticProps = async () => {
  const res = await fetch("https://restcountries.com/v3.1/all");
  const data = await res.json();

  return {
    props: { countries: data }
  }
}

const Home = ({ countries }) => {
  console.log(countries)
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Where in the world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main>
        {countries.map(country => (
            <div key={country.id}>
              <Image src={country.flags.svg} alt="A country flag" width={128} height={77} />
              <div>
                <div>
                  <h2>{country.name.official}</h2>
                </div>
                <div>
                  <h2>Population</h2>
                  <p>{country.population}</p>
                </div>
                <div>
                  <h2>Region</h2>
                  <p>{country.region}</p>
                </div>
                <div>
                  <h2>Capital</h2>
                  <p>{country.capital}</p>
                </div>
              </div>
            </div>
            // {console.log(country.population)}
          ))}
      </main>
    </div>
  );
}

export default Home;
