import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
// import { uuid } from "uuid"

export const getStaticProps = async () => {
  const { data } = await axios.get("https://restcountries.com/v3.1/all");
  const sortedData = data.sort((a, b) => {
    if (a.name.common < b.name.common) {
      return -1;
    } else if (a.name.common > b.name.common) {
      return 1;
    }
    return 0;
  });
  return {
    props: { countries: sortedData },
  };
};

const Home = ({ countries }) => {
  console.log(countries)
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Where in the world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main>
        {countries.map(country => (
            <Link href= {'/country/' + country.name.common.toLowerCase()} key={country.name.common}>
              <div>
              <Image src={country.flags.svg} alt="A country flag" width={128} height={77} />
                <div>
                  <h2>{country.name.common}</h2>
                </div>
                <div>
                  <h2>Population</h2>
                  <p>{country.population}</p>
                </div>
                <div>
                  <h2>Region</h2>
                  <p>{country.region}</p>
                </div>
                <div>
                  <h2>Capital</h2>
                  <p>{country.capital}</p>
                </div>
              </div>
            </Link>
            // {console.log(country.population)}
          ))}
      </main>
    </div>
  );
}

export default Home;
